name: GLFW Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional" -y
        choco install visualstudio2019-workload-vctools -y
      
    - name: Install C++ Build Tools
      run: |
        choco install visualstudio2022buildtools --package-parameters "--includeRecommended --includeOptional" -y

    - name: Restore dependencies
      run: |
        cd GLFW_EXAMPLE
        vcpkg install glfw3:x64-windows
        vcpkg install glew:x64-windows
        
    - name: Install MSBuild
      run: |
          choco install msbuild --version 15.0.27014.1 --pre -y
          $env:PATH = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\15.0\Bin;" + $env:PATH
      
    - name: Build Proj
      run: |
        cd GLFW_EXAMPLE
        MSBuild.exe GLFW_EXAMPLE.sln /t:Build /p:Configuration=Release /p:Platform=x64
