name: CI-Build

on:
  push:
    branches:
      - master
    paths:
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.md'
  pull_request:
    branches:
      - master

jobs:
  CI-Build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Restore dependencies
      run: |
        cd GLFW_EXAMPLE
        vcpkg install glfw3:x64-windows
        vcpkg install glew:x64-windows
        
    - name: Restore NuGet packages
      run: nuget restore GLFW_Example.sln

    - name: Build project
      run: msbuild GLFW_Example.sln /p:Configuration=Debug
      
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: v1.0.4.2